// src/client/components/lobby/TeamPanel.tsx
import { For, Show } from "solid-js"
import type { TeamState } from "../../../shared/types"
import { Button } from "../ui/button"
import { Badge } from "../ui/badge"
import { cn } from "../../lib/cn"
import { clientId } from "../../stores/auth"

interface TeamPanelProps {
  team: "A" | "B"
  state: TeamState
  myTeam: "A" | "B" | null
  isHost?: boolean
  onJoin: () => void
  onLeave: () => void
  onKick?: (clientId: string) => void
  disabled?: boolean
}

export function TeamPanel(props: TeamPanelProps) {
  const isMyTeam = () => props.myTeam === props.team
  const teamEmoji = () => (props.team === "A" ? "🧊" : "🌟")
  const teamName = () => (props.team === "A" ? "крижані" : "зоряні")

  return (
    <div
      class={cn(
        "flex flex-col rounded-2xl p-4 transition-all glass inner-glow",
        props.team === "A" ? "team-a-top-accent" : "team-b-top-accent",
        isMyTeam() &&
          (props.team === "A"
            ? "shadow-[0_0_24px_rgba(96,165,250,0.12)]"
            : "shadow-[0_0_24px_rgba(251,191,36,0.12)]"),
      )}
    >
      <div class="flex items-center justify-between mb-3">
        <h3 class={cn("font-semibold flex items-center gap-1.5", props.team === "A" ? "text-team-a" : "text-team-b")}>
          {teamEmoji()} {teamName()}
        </h3>
        <Badge variant={props.team === "A" ? "team-a" : "team-b"}>{props.state.players.length}</Badge>
      </div>

      <div class="flex-1 space-y-1.5 mb-3 min-h-[72px]">
        <For each={props.state.players}>
          {(player) => (
            <div
              class={cn(
                "flex items-center gap-2 rounded-lg px-3 py-1.5 text-sm",
                player.clientId === clientId() ? "glass-light font-medium border border-white/[0.06]" : "bg-white/[0.03]",
                !player.connected && "opacity-40",
              )}
            >
              <span
                class={cn(
                  "w-1.5 h-1.5 rounded-full",
                  player.connected
                    ? "bg-success shadow-[0_0_6px_rgba(52,211,153,0.5)]"
                    : "bg-text-muted",
                )}
              />
              <span class="truncate">{player.nickname}</span>
              <Show when={player.isHost}>
                <span class="text-xs ml-auto">👑</span>
              </Show>
              <Show when={props.isHost && !player.isHost && player.clientId !== clientId()}>
                <button
                  class="ml-auto text-xs text-text-muted hover:text-danger transition-colors px-1"
                  onClick={() => props.onKick?.(player.clientId)}
                  title="вигнати"
                >
                  ✕
                </button>
              </Show>
            </div>
          )}
        </For>
        <Show when={props.state.players.length === 0}>
          <div class="text-xs text-text-muted text-center py-4">тут поки порожньо 🐧</div>
        </Show>
      </div>

      <Show when={!props.disabled}>
        <Show
          when={isMyTeam()}
          fallback={
            <Button
              variant={props.team === "A" ? "team-a" : "team-b"}
              size="sm"
              class="w-full"
              onClick={props.onJoin}
              disabled={props.myTeam !== null && props.myTeam !== props.team}
            >
              приєднатись
            </Button>
          }
        >
          <Button variant="ghost" size="sm" class="w-full" onClick={props.onLeave}>
            вийти
          </Button>
        </Show>
      </Show>
    </div>
  )
}

// src/client/components/lobby/TeamPanel.vue
<script setup lang="ts">
import { computed } from "vue"
import type { TeamState } from "../../../shared/types"
import { TEAM_COLORS } from "../../../shared/teams"
import { Button } from "../ui/button"
import { cn } from "../../lib/cn"
import { clientId } from "../../stores/auth"

const props = defineProps<{
  team: number
  state: TeamState
  myTeam: number | null
  isHost?: boolean
  disabled?: boolean
  scoreToWin?: number
  isCurrentTurn?: boolean
}>()

const emit = defineEmits<{
  join: []
  leave: []
  kick: [clientId: string]
  nameChange: [name: string]
}>()

const isMyTeam = computed(() => props.myTeam === props.team)
const canEditName = computed(() => isMyTeam.value && !props.disabled)
const teamColor = computed(() => TEAM_COLORS[props.team] ?? "#888")
const isGameMode = computed(() => props.scoreToWin != null)
const scorePercent = computed(() => {
  if (!props.scoreToWin) return 0
  return Math.min(100, (props.state.score / props.scoreToWin) * 100)
})
</script>

<template>
  <div
    :class="cn(
      'flex flex-col rounded-lg bg-card border overflow-hidden transition-all',
    )"
    :style="isCurrentTurn ? {
      borderColor: `${teamColor}66`,
      boxShadow: `0 0 16px ${teamColor}1a`,
    } : undefined"
  >
    <!-- Colored top strip -->
    <div class="h-1" :style="{ backgroundColor: teamColor }" />

    <div class="p-3 flex flex-col gap-2">
      <!-- Header: name + count -->
      <div class="flex items-center justify-between">
        <template v-if="canEditName">
          <input
            type="text"
            :value="state.name"
            maxlength="16"
            class="text-sm font-semibold bg-transparent border-b border-dashed border-border outline-none w-full mr-2"
            :style="{ color: teamColor }"
            @input="emit('nameChange', ($event.target as HTMLInputElement).value)"
          />
        </template>
        <template v-else>
          <span class="text-sm font-semibold" :style="{ color: teamColor }">
            {{ state.name }}
          </span>
        </template>
        <span
          v-if="!isGameMode"
          class="text-xs tabular-nums min-w-5 text-center font-medium text-muted-foreground"
        >
          {{ state.players.length }}
        </span>
      </div>

      <!-- Score (game mode) -->
      <template v-if="isGameMode">
        <div class="text-center py-1">
          <span class="text-3xl font-bold tabular-nums" :style="{ color: teamColor }">
            {{ state.score }}
          </span>
        </div>
        <div class="w-full h-1 rounded-full bg-secondary overflow-hidden">
          <div
            class="h-full rounded-full transition-all duration-500"
            :style="{
              width: `${scorePercent}%`,
              backgroundColor: teamColor,
            }"
          />
        </div>
      </template>

      <!-- Player list -->
      <div :class="isGameMode ? 'space-y-0.5 mt-1' : 'space-y-1 min-h-[52px]'">
        <div
          v-for="player in state.players"
          :key="player.clientId"
          :class="cn(
            'flex items-center gap-2 rounded-md text-xs',
            isGameMode ? 'px-1.5 py-0.5' : 'px-2.5 py-1 text-sm',
            player.clientId === clientId ? 'bg-secondary font-medium' : '',
            !player.connected && 'opacity-40',
          )"
        >
          <span
            :class="cn(
              'w-1.5 h-1.5 rounded-full shrink-0',
              player.connected ? 'bg-success' : 'bg-muted-foreground',
            )"
          />
          <span class="truncate">{{ player.nickname }}</span>
          <span v-if="player.isHost" class="text-[10px] ml-auto">👑</span>
          <button
            v-if="isHost && !player.isHost && player.clientId !== clientId && !disabled"
            class="ml-auto text-xs text-muted-foreground hover:text-destructive transition-colors px-0.5 cursor-pointer"
            @click="emit('kick', player.clientId)"
            title="вигнати"
          >
            ✕
          </button>
        </div>
        <p v-if="state.players.length === 0 && !isGameMode" class="text-xs text-muted-foreground text-center py-3">
          порожньо
        </p>
      </div>

      <!-- Action (lobby mode only) -->
      <template v-if="!disabled">
        <Button
          v-if="isMyTeam"
          variant="ghost"
          size="sm"
          class="w-full text-muted-foreground"
          @click="emit('leave')"
        >
          вийти
        </Button>
        <Button
          v-else
          variant="outline"
          size="sm"
          class="w-full"
          :style="{ color: teamColor, borderColor: `${teamColor}40` }"
          @click="emit('join')"
        >
          приєднатись
        </Button>
      </template>
    </div>
  </div>
</template>
